import { EPointType } from "../types"
import { POINT_TYPE_ICON } from "./pointTypeIcon"

export const POINT_TYPE_HINT: {
    [key in keyof typeof POINT_TYPE_ICON]?: string
} = {
    [EPointType.Water]: 'Water - Liquid that freezes below -2°C and boils above 99°C',
    [EPointType.Sand]: 'Sand - Basic particle affected by gravity',
    [EPointType.Stone]: 'Stone - Solid that melts into lava above 550°C',
    [EPointType.Lava]: 'Lava - Hot liquid that solidifies below 500°C',
    [EPointType.Metal]: 'Metal - Conducts electricity and melts above 550°C',
    [EPointType.Electricity_Ground]: 'Electricity Ground - Absorbs electrical charge',
    [EPointType.Electricity_Spark]: 'Electricity Spark - Moves chaotically and conducts electricity',
    [EPointType.Electricity_Source]: 'Electricity Source - Generates electrical charge',
    [EPointType.Electricity_Amplifier]: 'Electricity Amplifier - Multiplies electrical charge',
    [EPointType.Heater]: 'Heater - Consumes electricity to generate heat',
    [EPointType.Cooler]: 'Cooler - Consumes electricity to absorb heat',
    [EPointType.ColdDetector]: 'Cold Detector - Emits electricity when temperature falls below -50°C',
    [EPointType.HotDetector]: 'Hot Detector - Emits electricity when temperature rises above 90°C',
    [EPointType.LiquidDetector]: 'Liquid Detector - Emits electricity when in contact with liquids',
    [EPointType.Wood]: 'Wood - Burns at high temperatures (above 400°C)',
    [EPointType.Border]: 'Border - Immovable boundary element',
    [EPointType.Fire]: 'Fire - Short-lived hot element that burns nearby materials',
    [EPointType.IceFire]: 'Ice Fire - Cold fire that freezes nearby materials',
    [EPointType.Bomb]: 'Bomb - Explodes on contact',
    [EPointType.Dynamite]: 'Dynamite - Stationary explosive',
    [EPointType.Ice]: 'Ice - Solid water that melts above 0°C',
    [EPointType.Clone]: 'Clone - Copies adjacent elements',
    [EPointType.Gas]: 'Gas - Light particle that moves chaotically and ignites above 250°C',
    [EPointType.Void]: 'Void - Removes any element it touches',
    [EPointType.ConstantCold]: 'Constant Cold - Permanently emits extreme cold',
    [EPointType.ConstantHot]: 'Constant Hot - Permanently emits extreme heat',
    [EPointType.LiquidGas]: 'Liquid Gas - Cold liquid that evaporates easily',
    [EPointType.LiquidGlass]: 'Liquid Glass - Molten glass that solidifies at lower temperatures',
    [EPointType.Glass]: 'Glass - Transparent solid material',
    [EPointType.Virus]: 'Virus - Infects and transforms adjacent elements',
    [EPointType.Heal]: 'Heal - Neutralizes viruses and restores infected elements',
    [EPointType.Acid]: 'Acid - Corrosive liquid that dissolves various materials',
    [EPointType.PlantSeed]: 'Plant Seed - Grows into a plant when given the right conditions',
    [EPointType.Wire]: 'Wire - Creates a direct electrical connection between two points',
    [EPointType.Pipe]: 'Pipe - Creates a direct path for liquids to flow between two points',
    [EPointType.Snow]: 'Snow - Light particles that melt into water when heated above 0°C',
    [EPointType.Magnet]: 'Magnet - Dark-gray powder that is attracted to metal objects',
    [EPointType.WindSource]: 'Wind Source - Creates air currents that push lighter elements',
    eraser: 'Eraser - Removes elements from the simulation',
    heatTool: 'Heat Tool - Increases temperature of elements',
    coolTool: 'Cool Tool - Decreases temperature of elements',
} 